import {NextResponse} from "next/server";
import {getSessionUser} from "@/lib/outreach";
const agents=[
{id:"orchestrator",name:"COMIT Orchestrator",owner:"Amal",goal:"Route each business request to the correct intelligence workflow and enforce the evidence-to-action loop.",triggers:["any request"],outputs:["agent route","priority","next action"]},
{id:"win-strategy",name:"Win Strategy Agent",owner:"Amal",goal:"Convert research into a deal-specific path: trigger, pain hypothesis, proof, stakeholders, discovery, objections and next commitment.",triggers:["qualified account","proposal","stalled deal"],outputs:["win plan","research gaps","discovery plan","proof plan","close question"]},
{id:"prospect-research",name:"Prospect Research Agent",owner:"Aadil",goal:"Find, qualify and evidence new prospects using fit, intent and legitimate business signals.",triggers:["new prospect","daily research","buying signal"],outputs:["fit","trigger","pain hypothesis","stakeholders","next action"]},
{id:"outreach",name:"Outreach Agent",owner:"Amal",goal:"Create approval-gated personalized outreach and follow-up sequences.",triggers:["qualified prospect","follow-up due","no response"],outputs:["message","follow-up","close question"]},
{id:"restaurant-growth",name:"Restaurant Growth Agent",owner:"Aneesh",goal:"Turn restaurant research and live creative signals into a restaurant-specific growth plan using AI content, poster campaigns, local discovery, delivery-platform conversion, offers and repeat-customer follow-up.",triggers:["restaurant prospect","new restaurant","campaign refresh","delivery growth","local discovery"],outputs:["restaurant audit","creative angles","offer ideas","local SEO actions","campaign plan","next action"]},
{id:"marketing",name:"Marketing Intelligence Agent",owner:"Aneesh",goal:"Turn business goals into measurable campaign, content, funnel and creative actions.",triggers:["campaign","content","ads","SEO"],outputs:["campaign brief","content plan","KPI"]},
{id:"client-growth",name:"Client Growth Agent",owner:"Jishnu",goal:"Detect client growth opportunities, expansion signals, retention risks and next-best actions.",triggers:["client signal","weekly review"],outputs:["opportunity","risk","account action"]},
{id:"team-ops",name:"Team Operations Agent",owner:"Amal",goal:"Track tasks, blockers, workload, ownership and execution rhythm.",triggers:["task overdue","daily check-in"],outputs:["assignment","blocker","escalation"]},
{id:"revenue",name:"Revenue Intelligence Agent",owner:"Amal",goal:"Surface pipeline gaps, revenue opportunities, deal risk and win/loss learning.",triggers:["pipeline change","weekly review"],outputs:["KPI insight","opportunity","next-best action"]},
{id:"automation",name:"n8n Automation Agent",owner:"COMIT",goal:"Turn approved workflows into self-hosted/no-billing n8n executions.",triggers:["approved action","scheduled workflow"],outputs:["workflow event","execution status","audit event"]}
];
export async function GET(req:Request){if(!getSessionUser(req))return NextResponse.json({ok:false,error:"Authentication required"},{status:401});return NextResponse.json({ok:true,agents});}
export async function POST(req:Request){const u=getSessionUser(req);if(!u)return NextResponse.json({ok:false,error:"Authentication required"},{status:401});const b=await req.json().catch(()=>({}));const agent=agents.find(a=>a.id===b.agentId);if(!agent)return NextResponse.json({ok:false,error:"Unknown agent"},{status:404});return NextResponse.json({ok:true,status:"queued",agent,requestedBy:u.email,mode:process.env.N8N_COMIT_WEBHOOK_URL?"n8n":"no-billing",message:"Execution is approval-aware and can use self-hosted n8n without paid API usage."});}
