import {NextResponse} from "next/server";
import {getSessionUser} from "@/lib/outreach";
const agents=[
{id:"win-strategy",name:"Win Strategy Agent",owner:"Amal",goal:"Convert research into a deal-specific path: trigger → pain hypothesis → proof → stakeholders → discovery → objection handling → next commitment.",triggers:["qualified account","proposal stage","stalled deal","no response"],outputs:["win score","research gaps","discovery plan","proof plan","close question"]},
{id:"prospect-research",name:"Prospect Research Agent",owner:"Aadil",goal:"Find, qualify and evidence new prospects.",triggers:["new prospect","daily research","buying signal"] ,outputs:["fit","trigger","pain hypothesis","stakeholders","proof plan","next action"]},
{id:"outreach",name:"Outreach Agent",owner:"Amal",goal:"Turn researched accounts into approval-gated personalized outreach and follow-up sequences.",triggers:["qualified prospect","follow-up due","no response"] ,outputs:["message","objection hypothesis","follow-up","close question"]},
{id:"creative",name:"Creative Agency Agent",owner:"Aneesh",goal:"Turn client goals into poster, carousel and reel briefs.",triggers:["content request","campaign launch"]},
{id:"client-growth",name:"Client Growth Agent",owner:"Jishnu",goal:"Detect client growth opportunities, expansion signals and account risks; propose evidence-backed actions.",triggers:["client signal","weekly review"]},
{id:"team-ops",name:"Team Operations Agent",owner:"Amal",goal:"Track tasks, blockers, workload and healthy working rhythms.",triggers:["task overdue","daily check-in"]},
{id:"revenue",name:"Revenue Intelligence Agent",owner:"Amal",goal:"Surface pipeline gaps, deal risk, next-best actions and win/loss learning without inventing confidence.",triggers:["pipeline change","weekly revenue review"]}];
export async function GET(req:Request){if(!getSessionUser(req))return NextResponse.json({ok:false,error:"Authentication required"},{status:401});return NextResponse.json({ok:true,agents});}
export async function POST(req:Request){const u=getSessionUser(req);if(!u)return NextResponse.json({ok:false,error:"Authentication required"},{status:401});const b=await req.json().catch(()=>({}));const agent=agents.find(a=>a.id===b.agentId);if(!agent)return NextResponse.json({ok:false,error:"Unknown agent"},{status:404});return NextResponse.json({ok:true,status:"queued",agent,requestedBy:u.email,mode:"rule-engine",message:"Agent execution queued. Connect a free/self-hosted n8n worker for autonomous execution; COMIT will not create paid API usage."});}
