"use client";
import {useEffect,useState} from "react";

type Agent={id:string;name:string;purpose:string;owner:string;success:string};
type Job={id:string;status:string;input:{task:string;agent:string};output?:{owner?:string;model_draft?:string;model_mode?:string;approved_lessons?:string[];artifact?:{title:string;body:string;checks:string[]};brief?:{recommendation?:{experiment:string;kpi:string};research_gaps?:string[]};handoff?:{to:string;reason:string};external_action_taken?:boolean}};
type Message={id:string;event_type:string;aggregate_id:string;created_at:string;payload:{note?:string;handoff?:{to:string;reason:string}}};

export default function AgentHome(){
 const [agents,setAgents]=useState<Agent[]>([]),[jobs,setJobs]=useState<Job[]>([]),[messages,setMessages]=useState<Message[]>([]),[pending,setPending]=useState<Message[]>([]);
 const [task,setTask]=useState(""),[business,setBusiness]=useState(""),[agentId,setAgentId]=useState("auto"),[feedback,setFeedback]=useState<Record<string,string>>({});
 const [busy,setBusy]=useState(""),[error,setError]=useState("");
 async function load(){try{const r=await fetch("/api/agents",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Agent Home unavailable");setAgents(d.agents||[]);setJobs(d.jobs||[]);setMessages(d.messages||[]);setPending(d.pending_feedback||[])}catch(e){setError(e instanceof Error?e.message:"Agent Home unavailable")}}
 useEffect(()=>{void load()},[]);
 async function send(action:string,jobId?:string,extra:Record<string,string>={}){setBusy(jobId||"new");setError("");try{const body=action==="create"?{action,task,context:{business},agentId:agentId==="auto"?undefined:agentId}:{action,jobId,note:feedback[jobId||""],...extra};const r=await fetch("/api/agents",{method:"POST",headers:{"content-type":"application/json",...(action==="create"?{"x-idempotency-key":crypto.randomUUID()}: {})},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Action failed");if(action==="create")setTask("");if(action==="feedback")setFeedback(v=>({...v,[jobId||""]:""}));await load()}catch(e){setError(e instanceof Error?e.message:"Action failed")}finally{setBusy("")}}
 return <section className="mt-7 rounded-2xl border border-[var(--prism-border)] bg-[var(--prism-surface)] p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs uppercase tracking-wider text-violet-300">Agent Home · draft mode</p><h2 className="mt-1 text-xl font-semibold">Shared work, memory and review</h2><p className="mt-1 text-sm text-[var(--prism-muted)]">Tasks and agent messages are stored in COMIT. Nothing is emailed, published or changed in the CRM by these buttons.</p></div><button type="button" onClick={()=>void load()} className="rounded-lg border border-[var(--prism-border)] px-3 py-2 text-xs">Refresh</button></div>
  <div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{agents.map(a=><article key={a.id} className="rounded-xl border border-[var(--prism-border)] p-3"><p className="text-sm font-semibold">{a.name}</p><p className="mt-1 text-xs text-[var(--prism-muted)]">{a.purpose}</p><p className="mt-2 text-xs">Owner: {a.owner}</p></article>)}</div>
  <form onSubmit={e=>{e.preventDefault();void send("create")}} className="mt-5 grid gap-3 md:grid-cols-[1fr_11rem_11rem_auto]"><label className="text-xs text-[var(--prism-muted)]">New task<input required maxLength={2000} value={task} onChange={e=>setTask(e.target.value)} placeholder="A customer may cancel; draft a safe response" className="mt-1 w-full rounded-xl border border-[var(--prism-border)] bg-black/20 p-3 text-sm text-[var(--prism-text)]"/></label><label className="text-xs text-[var(--prism-muted)]">Business scope<input maxLength={120} value={business} onChange={e=>setBusiness(e.target.value)} placeholder="Client name" className="mt-1 w-full rounded-xl border border-[var(--prism-border)] bg-black/20 p-3 text-sm text-[var(--prism-text)]"/></label><label className="text-xs text-[var(--prism-muted)]">Route to<select value={agentId} onChange={e=>setAgentId(e.target.value)} className="mt-1 w-full rounded-xl border border-[var(--prism-border)] bg-black/20 p-3 text-sm text-[var(--prism-text)]"><option value="auto">Orchestrator</option>{agents.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><button disabled={!!busy} className="self-end rounded-xl bg-white px-4 py-3 text-sm font-semibold text-black disabled:opacity-50">Queue task</button></form>
  {error&&<p role="alert" className="mt-3 text-sm text-red-300">{error}</p>}
  {pending.length>0&&<div className="mt-5 rounded-xl border border-amber-500/30 p-4"><h3 className="text-sm font-semibold">Feedback awaiting founder review</h3>{pending.map(m=><div key={m.id} className="mt-3 flex flex-wrap items-center justify-between gap-2 text-xs"><span>{m.payload?.note||"Correction"}</span><div className="flex gap-2"><button disabled={!!busy} onClick={()=>void send("review_feedback",m.aggregate_id,{feedbackId:m.id,decision:"accept"})} className="rounded-lg border border-emerald-500/40 px-2 py-1">Approve for same business</button><button disabled={!!busy} onClick={()=>void send("review_feedback",m.aggregate_id,{feedbackId:m.id,decision:"reject"})} className="rounded-lg border border-red-500/40 px-2 py-1">Reject</button></div></div>)}</div>}
  <div className="mt-5 space-y-3">{jobs.map(j=><article key={j.id} className="rounded-xl border border-[var(--prism-border)] p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="text-sm font-medium">{j.input.task}</p><p className="mt-1 text-xs text-[var(--prism-muted)]">{j.input.agent} · {j.status} · {j.output?.owner||"owner assigned on draft"}</p></div><div className="flex gap-2">{j.status==="queued"&&<button disabled={!!busy} onClick={()=>void send("run",j.id)} className="rounded-lg border border-[var(--prism-border)] px-3 py-1.5 text-xs">Create draft</button>}{j.status==="awaiting_approval"&&<><button disabled={!!busy} onClick={()=>void send("approve",j.id)} className="rounded-lg border border-emerald-500/40 px-3 py-1.5 text-xs">Approve draft</button><button disabled={!!busy} onClick={()=>void send("reject",j.id)} className="rounded-lg border border-red-500/40 px-3 py-1.5 text-xs">Reject</button></>}</div></div>
   {j.output?.artifact&&<div className="mt-3 rounded-lg bg-white/5 p-3 text-sm"><p className="font-medium">{j.output.artifact.title}</p><p className="mt-1">{j.output.artifact.body}</p><p className="mt-2 text-xs text-[var(--prism-muted)]">Checks: {j.output.artifact.checks.join(" · ")}</p><p className="mt-2 text-xs text-[var(--prism-muted)]">KPI: {j.output.brief?.recommendation?.kpi}</p></div>}
   {j.output?.model_draft&&<div className="mt-2 rounded-lg border border-violet-400/30 p-3 text-sm"><p className="text-xs text-violet-300">Connected model draft · review every claim</p><p className="mt-2 whitespace-pre-wrap">{j.output.model_draft}</p></div>}
   {!!j.output?.approved_lessons?.length&&<p className="mt-2 text-xs text-[var(--prism-muted)]">Reviewed lessons for this business: {j.output.approved_lessons.join(" · ")}</p>}
   {j.output?.handoff&&<p className="mt-2 text-xs text-amber-200">Suggested handoff → {j.output.handoff.to}: {j.output.handoff.reason}</p>}
   <div className="mt-3 flex gap-2"><input aria-label={`Feedback for ${j.input.task}`} value={feedback[j.id]||""} onChange={e=>setFeedback(v=>({...v,[j.id]:e.target.value}))} placeholder="Record a correction or measured outcome" className="min-w-0 flex-1 rounded-lg border border-[var(--prism-border)] bg-black/20 px-3 py-2 text-xs"/><button disabled={!!busy||!(feedback[j.id]||"").trim()} onClick={()=>void send("feedback",j.id)} className="rounded-lg border border-[var(--prism-border)] px-3 py-2 text-xs">Record</button></div>
   {messages.filter(m=>m.aggregate_id===j.id).slice(0,5).map(m=><p key={m.id} className="mt-2 text-xs text-[var(--prism-muted)]">{m.event_type} · {new Date(m.created_at).toLocaleString()}{m.payload?.note?` · ${m.payload.note}`:""}</p>)}
  </article>)}{jobs.length===0&&<p className="text-sm text-[var(--prism-muted)]">No agent tasks yet. Queue one above to start.</p>}</div></section>;
}
