"use client";
import {useState} from "react";
import {ArrowLeft,Clipboard, Sparkles} from "lucide-react";

type Plan={ok:boolean;error?:string;mode:string;lane:string;confidence:string;summary:string;objective:string;known:{label:string;value:string}[];assumptions:string[];research_gaps:string[];recommendation:{experiment:string;owner:string;steps:string[];kpi:string;baseline:string;target:string;review:string;change_rule:string};constraints:string;approval:string;learning:string;automation?:string;result?:unknown};
const fields=[{key:"business",label:"Business or client",placeholder:"Nostaza Restaurant"},{key:"objective",label:"Outcome to improve",placeholder:"More repeat orders"},{key:"evidence",label:"Evidence and source",placeholder:"What have you observed? Include a source or date."},{key:"baseline",label:"Current baseline",placeholder:"e.g. 12 attributed orders last week"},{key:"target",label:"Target",placeholder:"e.g. 18 attributed orders in two weeks"},{key:"constraints",label:"Constraints",placeholder:"Budget, available footage, delivery area…"},{key:"outcome",label:"Result from a previous test",placeholder:"What happened, and how was it measured?"}] as const;
type Key=typeof fields[number]["key"];

export default function AgentsPage(){
  const [message,setMessage]=useState("");
  const [context,setContext]=useState<Record<Key,string>>({business:"",objective:"",evidence:"",baseline:"",target:"",constraints:"",outcome:""});
  const [plan,setPlan]=useState<Plan|null>(null);
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState("");
  async function run(event:React.FormEvent){event.preventDefault();setBusy(true);setError("");setPlan(null);try{const response=await fetch("/api/ai",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message,context})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Could not create a plan.");setPlan(data)}catch(e){setError(e instanceof Error?e.message:"Could not create a plan.")}finally{setBusy(false)}}
  async function copy(){if(plan)await navigator.clipboard.writeText(JSON.stringify(plan,null,2))}
  return <main className="min-h-screen bg-[var(--prism-bg)] p-5 text-[var(--prism-text)] lg:p-8"><div className="mx-auto max-w-6xl"><a href="/" className="inline-flex items-center gap-2 text-sm text-[var(--prism-muted)]"><ArrowLeft size={15}/>Command Center</a><header className="mt-6"><p className="text-xs tracking-widest text-violet-300">COMIT · STRATEGY WORKSPACE</p><h1 className="mt-2 text-3xl font-semibold">Turn evidence into the next move</h1><p className="mt-2 max-w-2xl text-sm text-[var(--prism-muted)]">Build one measurable experiment for sales, marketing, restaurants, creative, finance or team operations. Runs without a paid AI API.</p></header>
  <div className="mt-7 grid gap-6 lg:grid-cols-[.9fr_1.1fr]"><form onSubmit={run} className="space-y-4 rounded-2xl border border-[var(--prism-border)] bg-[var(--prism-surface)] p-5"><label className="block text-sm font-medium">What decision do you need to make?<textarea required maxLength={2000} rows={4} value={message} onChange={e=>setMessage(e.target.value)} placeholder="How can we increase qualified enquiries for this client?" className="mt-2 w-full rounded-xl border border-[var(--prism-border)] bg-black/20 p-3 text-sm outline-none"/></label><div className="grid gap-3 sm:grid-cols-2">{fields.map(f=><label key={f.key} className={`block text-xs text-[var(--prism-muted)] ${["evidence","constraints","outcome"].includes(f.key)?"sm:col-span-2":""}`}>{f.label}<input maxLength={f.key==="evidence"?800:400} value={context[f.key]} onChange={e=>setContext(v=>({...v,[f.key]:e.target.value}))} placeholder={f.placeholder} className="mt-1 w-full rounded-xl border border-[var(--prism-border)] bg-black/20 px-3 py-2.5 text-sm text-[var(--prism-text)] outline-none"/></label>)}</div><button disabled={busy} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-white p-3 text-sm font-semibold text-black disabled:opacity-50"><Sparkles size={16}/>{busy?"Building plan…":"Build a measurable plan"}</button>{error&&<p role="alert" className="text-sm text-red-300">{error}</p>}</form>
  <section aria-live="polite" className="rounded-2xl border border-[var(--prism-border)] bg-[var(--prism-surface)] p-5">{!plan?<div className="grid min-h-72 place-items-center text-center text-sm text-[var(--prism-muted)]">Your plan will show its evidence, assumptions, owner, experiment and measurement gaps here.</div>:plan.mode==="n8n"?<><h2 className="text-lg font-semibold">Connected workflow result</h2><p className="mt-2 text-xs text-[var(--prism-muted)]">Review before acting. No message or campaign is sent from this page.</p><pre className="mt-4 overflow-auto whitespace-pre-wrap break-words rounded-xl border border-[var(--prism-border)] p-4 text-xs">{JSON.stringify(plan.result,null,2)}</pre></>:<><div className="flex items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-wider text-violet-300">{plan.lane} · {plan.mode}</p><h2 className="mt-2 text-xl font-semibold">{plan.objective}</h2><p className="mt-1 text-xs text-[var(--prism-muted)]">{plan.confidence}</p></div><button onClick={()=>void copy()} title="Copy plan" className="rounded-lg border border-[var(--prism-border)] p-2"><Clipboard size={16}/></button></div><div className="mt-5 rounded-xl border border-violet-400/25 bg-violet-500/5 p-4"><p className="text-xs text-violet-300">RECOMMENDED EXPERIMENT · OWNER: {plan.recommendation.owner}</p><p className="mt-2 font-medium">{plan.recommendation.experiment}</p><ol className="mt-3 list-decimal space-y-1 pl-5 text-sm text-[var(--prism-muted)]">{plan.recommendation.steps.map(s=><li key={s}>{s}</li>)}</ol></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{[["KPI",plan.recommendation.kpi],["Baseline",plan.recommendation.baseline],["Target",plan.recommendation.target],["Review",plan.recommendation.review]].map(([k,v])=><div key={k} className="rounded-xl border border-[var(--prism-border)] p-3"><p className="text-xs text-[var(--prism-muted)]">{k}</p><p className="mt-1 text-sm">{v}</p></div>)}</div><h3 className="mt-5 text-sm font-semibold">Evidence supplied</h3><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-[var(--prism-muted)]">{plan.known.length?plan.known.map(x=><li key={x.label}>{x.label}: {x.value}</li>):<li>No evidence supplied yet.</li>}</ul><h3 className="mt-5 text-sm font-semibold">Verify before acting</h3><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-[var(--prism-muted)]">{[...plan.assumptions,...plan.research_gaps].map(s=><li key={s}>{s}</li>)}</ul><p className="mt-5 text-xs text-[var(--prism-muted)]">{plan.recommendation.change_rule} {plan.approval} {plan.learning}</p></>}</section></div></div></main>
}
