(()=>{
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
async function monitoringData(){const r=await fetch('/api/monitoring/summary',{cache:'no-store'});if(!r.ok)throw new Error('Monitoring access failed');return r.json()}
function monitoringPage(){return '<div class="card hero"><div class="ey">ORBIT · LIVE OBSERVABILITY</div><h2>Performance & Improvement Center</h2><p>Monitor request health, latency, errors, memory and the endpoints that need attention.</p><div class="toolbar"><button class="btn primary" onclick="monitoringRefresh()">↻ Refresh</button><span id="monUpdated" class="muted">Waiting for data…</span></div></div><div id="monCards" class="grid g4" style="margin-top:12px"></div><div class="grid g2" style="margin-top:12px"><div class="card"><div class="ey">ENDPOINT PERFORMANCE</div><div id="monRoutes"></div></div><div class="card"><div class="ey">RECENT ERRORS</div><div id="monErrors"></div></div></div><div class="card" style="margin-top:12px"><div class="ey">IMPROVEMENT ENGINE</div><div id="monAdvice"></div></div>'}
function metricCard(label,value,sub){return '<div class="card"><div class="muted">'+label+'</div><div class="metric">'+value+'</div><small class="muted">'+sub+'</small></div>'}
function renderMonitoring(d){document.getElementById('monCards').innerHTML=metricCard('Requests',d.requests.total,'Since process start')+metricCard('Error rate',(d.requests.error_rate*100).toFixed(2)+'%',d.requests.errors+' server errors')+metricCard('Memory',d.resources.rss_mb+' MB','RSS in current process')+metricCard('Uptime',Math.floor(d.uptime_seconds/3600)+'h '+Math.floor(d.uptime_seconds%3600/60)+'m','Process uptime');
const routes=d.requests.routes||[];document.getElementById('monRoutes').innerHTML=routes.slice(0,15).map(r=>'<div class="row"><span><b>'+esc(r.path)+'</b><small class="muted" style="display:block">'+r.count+' requests · '+r.errors+' errors</small></span><span class="tag '+(r.avgMs>1000?'amber':'')+'">'+r.avgMs+' ms avg</span></div>').join('')||'<div class="muted">No requests recorded yet.</div>';
const errs=d.recent_errors||[],client=d.client_errors||[];document.getElementById('monErrors').innerHTML=errs.map(e=>'<div class="row"><span><b>'+esc(e.method+' '+e.path)+'</b><small class="muted" style="display:block">'+esc(e.at)+'</small></span><span class="tag">'+e.status+' · '+e.duration+' ms</span></div>').join('')||'<div class="muted">No 5xx errors recorded.</div>';if(client.length){document.getElementById('monErrors').innerHTML+='<div class="ey" style="margin-top:14px">CLIENT ERRORS</div>'+client.slice(0,8).map(e=>'<div class="row"><span><b>'+esc(e.kind)+' · '+esc(e.message)+'</b><small class="muted" style="display:block">'+esc(e.user||'')+' · '+esc(e.path||'/')+' · '+esc(e.at)+'</small></span><span class="tag amber">UI</span></div>').join('')}
const advice=[];routes.filter(r=>r.avgMs>500).slice(0,3).forEach(r=>advice.push('Investigate '+r.path+': average latency is '+r.avgMs+' ms.'));if(d.requests.error_rate>0.02)advice.push('Error rate is above 2%; inspect recent server errors before adding new features.');if(d.resources.rss_mb>300)advice.push('Memory is above 300 MB; inspect retained objects and long-lived caches.');if(!d.gmail.configured)advice.push('Gmail OAuth credentials are not configured in production yet.');if(!advice.length)advice.push('No immediate application-level bottleneck detected. Keep monitoring after real user traffic increases.');document.getElementById('monAdvice').innerHTML=advice.map(x=>'<div class="row"><span>• '+esc(x)+'</span></div>').join('');document.getElementById('monUpdated').textContent='Updated '+new Date().toLocaleTimeString()}
window.monitoringRefresh=async()=>{try{renderMonitoring(await monitoringData())}catch(e){document.getElementById('monUpdated').textContent=e.message}};
window.monitoringPage=monitoringPage;window.renderMonitoring=()=>window.monitoringRefresh();
const nav=document.getElementById('nav'),bottom=document.getElementById('bottom');if(nav&&!nav.querySelector('[data-k="monitoring"]'))nav.insertAdjacentHTML('beforeend','<button data-k="monitoring" onclick="show(\'monitoring\')"><i>📈</i>Performance Monitor</button>');if(bottom&&!bottom.querySelector('[data-k="monitoring"]'))bottom.insertAdjacentHTML('beforeend','<button data-k="monitoring" onclick="show(\'monitoring\')"><b>📈</b>Monitor</button>');
const oldShow=window.show;if(oldShow&&!window.__monitoringWrapped){window.__monitoringWrapped=true;window.show=function(k){oldShow(k);if(k==='monitoring')setTimeout(()=>monitoringRefresh(),0)}};
})();