"use client";
import {useCallback,useEffect,useState} from "react";
import {ArrowUpRight,CloudUpload,Film,FolderOpen,LoaderCircle,Plus,RefreshCw,Tags} from "lucide-react";

type Item={id:string;title:string;category:string;mime_type:string;file_size:number;notes:string;tags:string[];created_by:string;created_at:string;url:string|null};
const categories=[["shoot-footage","Video shoot footage"],["production","Production"],["edit","Edits"],["spot-edit","Spot edits"],["ai-reference","AI creative reference"],["final-delivery","Final delivery"],["other","Other"]];
export default function CreativeLibrary(){
 const [items,setItems]=useState<Item[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const [title,setTitle]=useState(""),[category,setCategory]=useState("shoot-footage"),[notes,setNotes]=useState(""),[tags,setTags]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await fetch("/api/creative-library",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not load the cloud library.");setItems(d.items||[])}catch(e:any){setError(e.message||"Could not load the cloud library.")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 async function upload(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;if(!form.reportValidity())return;setBusy(true);setError("");setNotice("");try{const data=new FormData(form);const r=await fetch("/api/creative-library",{method:"POST",body:data});const d=await r.json();if(!r.ok)throw new Error(d.error||"Upload failed.");setTitle("");setNotes("");setTags("");form.reset();setCategory("shoot-footage");setNotice("Saved to the shared COMIT cloud library.");await load()}catch(e:any){setError(e.message||"Upload failed.")}finally{setBusy(false)}}
 const size=(n:number)=>n>1024**3?(n/1024**3).toFixed(1)+" GB":n>1024**2?(n/1024**2).toFixed(1)+" MB":Math.max(1,Math.round(n/1024))+" KB";
 return <main className="min-h-screen bg-[var(--prism-bg)] text-[var(--prism-text)]"><div className="mx-auto max-w-6xl p-5 lg:p-8">
  <nav className="mb-6 flex flex-wrap gap-2 text-sm"><a href="/" className="text-[var(--prism-muted)]">Command Center</a><span>/</span><a href="/team" className="text-[var(--prism-muted)]">Team</a><span>/</span><span>Creative Library</span></nav>
  <header className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm text-[var(--prism-muted)]">VIDEO SHOOTS · PRODUCTION · AI CREATIVE</p><h1 className="mt-1 text-3xl font-semibold">Creative Cloud Library</h1><p className="mt-2 max-w-2xl text-sm text-[var(--prism-muted)]">A shared, evolving home for shoot footage, production files, edits, spot edits, AI references and approved final assets.</p></div><button onClick={()=>void load()} className="inline-flex items-center gap-2 self-start rounded-xl border border-[var(--prism-border)] px-3 py-2 text-sm"><RefreshCw size={15}/>Refresh library</button></header>
  <div className="mt-6 grid gap-5 lg:grid-cols-[minmax(280px,.85fr)_1.4fr]">
   <form onSubmit={upload} className="h-fit rounded-2xl border border-[var(--prism-border)] bg-[var(--prism-surface)] p-5"><div className="flex items-center gap-2"><CloudUpload size={18}/><h2 className="font-medium">Add a creative asset</h2></div><p className="mt-2 text-xs text-[var(--prism-muted)]">Private shared storage · videos up to 500 MB · MP4, MOV, WebM, images or PDF</p>
    <label className="mt-4 block text-xs">Asset title<input name="title" required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Nostaza launch shoot · hero take" className="mt-1 w-full rounded-xl border border-[var(--prism-border)] bg-transparent p-3 text-sm"/></label>
    <label className="mt-3 block text-xs">Library stage<select name="category" value={category} onChange={e=>setCategory(e.target.value)} className="mt-1 w-full rounded-xl border border-[var(--prism-border)] bg-[var(--prism-surface)] p-3 text-sm">{categories.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
    <label className="mt-3 block text-xs">File<input name="file" required type="file" accept="video/mp4,video/quicktime,video/webm,image/jpeg,image/png,image/webp,application/pdf" className="mt-1 w-full rounded-xl border border-[var(--prism-border)] p-3 text-xs"/></label>
    <label className="mt-3 block text-xs">Tags <span className="text-[var(--prism-muted)]">· comma separated</span><input name="tags" maxLength={400} value={tags} onChange={e=>setTags(e.target.value)} placeholder="client, campaign, vertical, v1" className="mt-1 w-full rounded-xl border border-[var(--prism-border)] bg-transparent p-3 text-sm"/></label>
    <label className="mt-3 block text-xs">Production notes / AI prompt<textarea name="notes" maxLength={4000} value={notes} onChange={e=>setNotes(e.target.value)} rows={4} placeholder="Shoot context, edit instructions, prompt, approvals or next iteration…" className="mt-1 w-full rounded-xl border border-[var(--prism-border)] bg-transparent p-3 text-sm"/></label>
    <button disabled={busy} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-semibold text-black disabled:opacity-60">{busy?<LoaderCircle className="animate-spin" size={16}/>:<Plus size={16}/>} {busy?"Uploading…":"Add to shared library"}</button>
   </form>
   <section><div className="mb-3 flex items-center justify-between"><div><h2 className="font-medium">Shared assets</h2><p className="text-xs text-[var(--prism-muted)]">Newest first · signed private links expire after one hour</p></div><span className="rounded-full border border-[var(--prism-border)] px-3 py-1 text-xs">{items.length} assets</span></div>
    {notice&&<p role="status" className="mb-3 rounded-xl border border-emerald-400/20 bg-emerald-400/5 p-3 text-sm">{notice}</p>}{error&&<p role="alert" className="mb-3 rounded-xl border border-rose-400/20 bg-rose-400/5 p-3 text-sm">{error}</p>}
    {loading?<div className="flex items-center gap-2 p-8 text-sm text-[var(--prism-muted)]"><LoaderCircle className="animate-spin" size={16}/>Loading shared library…</div>:items.length===0?<div className="rounded-2xl border border-dashed border-[var(--prism-border)] p-8 text-center"><FolderOpen className="mx-auto text-[var(--prism-muted)]" size={24}/><p className="mt-3 font-medium">Your creative library is ready</p><p className="mt-1 text-sm text-[var(--prism-muted)]">Add the first shoot file, edit, final or AI reference. New stages can be added as the workflow evolves.</p></div>:<div className="grid gap-3 sm:grid-cols-2">{items.map(item=><article key={item.id} className="rounded-2xl border border-[var(--prism-border)] bg-[var(--prism-surface)] p-4"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-violet-300/20 bg-violet-300/5"><Film size={18}/></div><div className="min-w-0"><h3 className="truncate text-sm font-medium">{item.title}</h3><p className="text-xs text-[var(--prism-muted)]">{categories.find(x=>x[0]===item.category)?.[1]||item.category} · {size(item.file_size)}</p></div></div>{item.url&&<a href={item.url} target="_blank" rel="noreferrer" aria-label={"Open "+item.title} className="rounded-lg border border-[var(--prism-border)] p-2"><ArrowUpRight size={15}/></a>}</div>{item.notes&&<p className="mt-3 whitespace-pre-wrap text-xs text-[var(--prism-muted)]">{item.notes}</p>}{item.tags?.length>0&&<div className="mt-3 flex flex-wrap gap-1">{item.tags.map(tag=><span key={tag} className="inline-flex items-center gap-1 rounded-full border border-[var(--prism-border)] px-2 py-1 text-[10px]"><Tags size={10}/>{tag}</span>)}</div>}<p className="mt-3 text-[10px] text-[var(--prism-muted)]">{new Date(item.created_at).toLocaleString()} · {item.created_by}</p></article>)}</div>}
   </section>
  </div>
 </div></main>
}
