// Public business details reviewed on 26 September 2026. Opportunities are hypotheses.
export const PROSPECT_BATCH = "2026-09-26-dubai";
export const todayProspects = [
  {id:"research-20260926-tiramisu",name:"Tiramisu Cafe",email:"hello@tiramisu.cafe",industry:"Cafe",location:"Downtown Dubai",source:"https://www.tiramisu.cafe/",notes:"Verified 26 Sep 2026: official site publishes this email and Downtown location; its FAQ contains placeholder text and inconsistent opening hours. Opportunity hypothesis: propose a website content cleanup and a dessert video concept. Confirm current hours and decision maker first."},
  {id:"research-20260926-creamio",name:"Creamio",email:"info@creamio.com",industry:"Cafe and gelato",location:"Jumeirah 3, Dubai",source:"https://www.creamio.com/",notes:"Verified 26 Sep 2026: official site lists pastries, gelato, this email and Triple 777 Center location. A footer still contains theme placeholder copy. Opportunity hypothesis: offer a small website polish and product video pilot. Existing agency credit is visible; do not assume they need a new provider."},
  {id:"research-20260926-lila",name:"Lila Molino",email:"hello@lilamolino.com",industry:"Mexican cafe and catering",location:"Alserkal Avenue, Dubai",source:"https://www.lilamolino.com/",notes:"Verified 26 Sep 2026: official site lists catering, delivery and the Alserkal Avenue location with this email. Opportunity hypothesis: a short tortilla-making shoot and a catering enquiry landing page. No buying intent or marketing deficiency verified."},
  {id:"research-20260926-bellini",name:"Bellini Cafe",email:"info@bellinicafe.com",industry:"Restaurant and private dining",location:"Jumeirah 2, Dubai",source:"https://bellinicafe.com/",notes:"Verified 26 Sep 2026: official site advertises private dining and catering with this enquiry email. Opportunity hypothesis: an event-experience film and a measurable private-dining enquiry campaign. Verify brand approval process and existing agency arrangements."},
  {id:"research-20260926-limetree",name:"The Lime Tree Cafe",email:"info@limetreecafe.ae",industry:"Cafe and catering",location:"Dubai — multiple locations",source:"https://www.thelimetreecafe.com/",notes:"Verified 26 Sep 2026: official site publishes this general email, multiple Dubai locations and catering/hampers offers. Opportunity hypothesis: seasonal hamper photography and corporate catering content. The original Jumeirah cafe is listed as closed; use current locations only."},
].map(p=>({...p,stage:"research",score:100}));
