"use client";
import {useEffect,useState} from "react";
import {Activity,ArrowUpRight,Bell,Bot,CheckCircle2,Copy,ExternalLink,Globe,Instagram,Mail,MessageCircle,Play,RefreshCw,ShieldCheck,Sparkles,Target,Users,Zap} from "lucide-react";

const links=[["/","Command Center"],["/outreach","Revenue"],["/prospects","Prospects"],["/team","Team"],["/agents","AI Agents"],["/creative","Creative"],["/integrations","Integrations"]];
const pitch="Lunes AI is intelligence that drives business growth — automating financial and digital operations, testing what works, and bringing the important parts of a business together at your fingertips.";

export default function CommandCenter(){
 const [health,setHealth]=useState("checking"),[nudge,setNudge]=useState(""),[deferredPrompt,setDeferredPrompt]=useState<any>(null),[aiInput,setAiInput]=useState(""),[aiResult,setAiResult]=useState<any>(null),[aiBusy,setAiBusy]=useState(false),[copied,setCopied]=useState(false),[healthBusy,setHealthBusy]=useState(false);
 useEffect(()=>{checkHealth();fetch("/api/notifications").then(r=>r.json()).then(d=>setNudge(d.nudge||"")).catch(()=>{});const handler=(e:any)=>{e.preventDefault();setDeferredPrompt(e)};window.addEventListener("beforeinstallprompt",handler);return()=>window.removeEventListener("beforeinstallprompt",handler)},[]);
 async function checkHealth(){setHealthBusy(true);try{const r=await fetch("/api/health",{cache:"no-store"});setHealth(r.ok?"healthy":"offline")}catch{setHealth("offline")}finally{setHealthBusy(false)}}
 async function install(){if(deferredPrompt){await deferredPrompt.prompt();await deferredPrompt.userChoice;setDeferredPrompt(null)}else alert("Use your browser menu → Install COMIT / Add to Home Screen.")}
 async function askAI(){if(!aiInput.trim())return;setAiBusy(true);try{const r=await fetch("/api/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:`You are COMIT, the internal growth operating system for Lunes AI. Lunes AI is an AI product designed to increase financial and digital growth through automation, testing and unified business operations. Answer with practical next actions. User request: ${aiInput}`})});setAiResult(await r.json())}catch{setAiResult({ok:false,error:"COMIT AI request failed"})}finally{setAiBusy(false)}}
 async function copyPitch(){try{await navigator.clipboard.writeText(pitch);setCopied(true);setTimeout(()=>setCopied(false),1600)}catch{alert(pitch)}}
 function focusAI(){document.getElementById("intelligence")?.scrollIntoView({behavior:"smooth"});setTimeout(()=>document.getElementById("ai-input")?.focus(),350)}
 async function notify(){if(!(typeof Notification!=="undefined"))return;const p=Notification.permission==="granted"?"granted":await Notification.requestPermission();if(p==="granted")new Notification("COMIT × Lunes AI",{body:nudge||"Choose the next action that can create measurable growth."})}
 return <main className="min-h-screen bg-[var(--prism-bg)] text-[var(--prism-text)]">
  <aside className="fixed hidden h-screen w-64 border-r border-[var(--prism-border)] bg-[var(--prism-surface)] p-5 lg:block">
   <div className="mb-8 flex items-center gap-3"><div className="orbit-gradient grid h-10 w-10 place-items-center rounded-xl text-lg font-black text-white">L</div><div><div className="font-semibold tracking-wide">Lunes AI</div><div className="text-xs text-[var(--prism-muted)]">COMIT Growth OS</div></div></div>
   <nav className="space-y-1">{links.map(([href,label],i)=><a key={href} href={href} className={'block rounded-xl px-3 py-2 text-sm transition '+(i===0?'bg-white/8 text-white':'text-[var(--prism-muted)] hover:bg-white/5 hover:text-white')}>{label}</a>)}</nav>
   <div className="mt-8 rounded-2xl border border-[var(--prism-border)] bg-white/[.02] p-4 text-xs leading-5 text-[var(--prism-muted)]"><span className="text-white">COMIT mission</span><br/>Turn Lunes AI from product → demand → demos → customers → measurable growth.</div>
  </aside>
  <section className="lg:pl-64">
   <header className="sticky top-0 z-20 flex flex-wrap items-center justify-between gap-3 border-b border-[var(--prism-border)] bg-[var(--prism-bg)]/90 px-5 py-4 backdrop-blur lg:px-8">
    <div><p className="text-xs font-medium tracking-[.2em] text-[var(--prism-cyan)]">LUNES AI · GO-TO-MARKET CONTROL</p><h1 className="text-xl font-semibold">COMIT Command Center</h1></div>
    <div className="flex items-center gap-2"><button onClick={checkHealth} disabled={healthBusy} className="flex items-center gap-2 rounded-full border border-[var(--prism-border)] px-3 py-2 text-xs hover:bg-white/5"><span className={'h-2 w-2 rounded-full '+(health==="healthy"?"bg-emerald-400":health==="offline"?"bg-red-400":"bg-amber-400")}/>{health}<RefreshCw size={12} className={healthBusy?"animate-spin":""}/></button><button onClick={notify} title="Team notification" className="rounded-xl border border-[var(--prism-border)] p-2 hover:bg-white/5"><Bell size={16}/></button><button onClick={install} className="orbit-gradient rounded-xl px-3 py-2 text-xs font-semibold text-white shadow-lg">Install app</button></div>
   </header>
   <div className="p-5 lg:p-8">
    <section className="orbit-glow relative overflow-hidden rounded-[2rem] border border-blue-400/20 bg-[var(--prism-surface)] p-6 lg:p-10"><div className="absolute -right-24 -top-24 h-72 w-72 rounded-full bg-blue-500/15 blur-3xl"/><div className="relative grid gap-8 lg:grid-cols-[1.2fr_.8fr] lg:items-center"><div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-blue-400/20 bg-blue-400/5 px-3 py-1 text-xs text-blue-200"><Sparkles size={13}/> Intelligence that drives growth</div><h2 className="max-w-3xl text-4xl font-semibold leading-tight tracking-tight lg:text-6xl">Build, operate and grow a business from your fingertips.</h2><p className="mt-5 max-w-2xl text-base leading-7 text-[var(--prism-muted)] lg:text-lg">Lunes AI is designed to increase financial and digital growth through automation, continuous testing and one connected operating layer for the business.</p><div className="mt-7 flex flex-wrap gap-3"><button onClick={focusAI} className="orbit-gradient flex items-center gap-2 rounded-xl px-5 py-3 text-sm font-semibold text-white"><Play size={15}/> Create a growth action</button><button onClick={copyPitch} className="flex items-center gap-2 rounded-xl border border-[var(--prism-border)] bg-white/[.03] px-5 py-3 text-sm hover:bg-white/5"><Copy size={15}/>{copied?"Pitch copied":"Copy Lunes AI pitch"}</button></div></div><div className="relative mx-auto w-full max-w-sm"><div className="aspect-square rounded-full border border-blue-400/30 bg-[radial-gradient(circle_at_50%_45%,rgba(47,107,255,.24),transparent_48%),#02050d] shadow-[0_0_100px_rgba(47,107,255,.2)]"><div className="absolute inset-[13%] rounded-full border border-white/10"/><div className="absolute inset-[25%] rounded-full border border-blue-300/15"/><div className="absolute inset-0 grid place-items-center"><div className="text-center"><div className="text-3xl font-bold">Lunes <span className="text-blue-400">AI</span></div><div className="mt-2 text-xs tracking-[.25em] text-[var(--prism-muted)]">GROWTH INTELLIGENCE</div></div></div></div></div></div></section>
    <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Demand","Find + qualify prospects",Target,"/prospects"],["Revenue","Cold outreach + follow-ups",Mail,"/outreach"],["Operations","Owners + daily execution",Users,"/team"],["Intelligence","Agents + learning loops",Bot,"/agents"]].map(([label,desc,Icon,href])=><a href={href as string} key={label as string} className="rounded-2xl border border-[var(--prism-border)] bg-[var(--prism-surface)] p-5 transition hover:-translate-y-0.5 hover:border-blue-400/30 hover:bg-white/[.03]"><Icon className="text-[var(--prism-cyan)]" size={19}/><div className="mt-4 font-medium">{label}</div><div className="mt-1 text-xs text-[var(--prism-muted)]">{desc}</div><ArrowUpRight size={14} className="mt-4 text-[var(--prism-muted)]"/></a>)}</div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.35fr_1fr]">
     <section className="rounded-2xl border border-[var(--prism-border)] bg-[var(--prism-surface)] p-5"><div className="flex items-center justify-between"><div><p className="text-xs tracking-[.18em] text-[var(--prism-cyan)]">PRODUCT NORTH STAR</p><h2 className="mt-1 font-medium">What COMIT must make true for Lunes AI</h2></div><Zap size={18} className="text-blue-300"/></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{[["1 · Discover","Research industries, pain points and ideal customers."],["2 · Prove","Run experiments and collect evidence of value."],["3 · Convert","Turn qualified interest into demos and customers."],["4 · Expand","Track outcomes and identify financial + digital growth opportunities."]].map(([a,b])=><div key={a} className="rounded-xl border border-[var(--prism-border)] p-4"><div className="text-sm font-medium">{a}</div><div className="mt-1 text-xs leading-5 text-[var(--prism-muted)]">{b}</div></div>)}</div></section>
     <section className="rounded-2xl border border-[var(--prism-border)] bg-[var(--prism-surface)] p-5"><div className="flex items-center gap-2"><ShieldCheck size={17}/><h2 className="font-medium">Quick actions</h2></div><div className="mt-4 space-y-2"><a href="/prospects" className="flex items-center justify-between rounded-xl border border-[var(--prism-border)] p-3 text-sm hover:bg-white/5">Review prospects<Target size={15}/></a><a href="/outreach" className="flex items-center justify-between rounded-xl border border-[var(--prism-border)] p-3 text-sm hover:bg-white/5">Open revenue pipeline<ArrowUpRight size={15}/></a><a href="/team" className="flex items-center justify-between rounded-xl border border-[var(--prism-border)] p-3 text-sm hover:bg-white/5">Open team operating lanes<Users size={15}/></a><a href="/integrations" className="flex items-center justify-between rounded-xl border border-[var(--prism-border)] p-3 text-sm hover:bg-white/5">Manage integrations<ExternalLink size={15}/></a><a href="https://prismofstories.com" target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-xl border border-[var(--prism-border)] p-3 text-sm hover:bg-white/5">Prism of Stories<Globe size={15}/></a></div></section>
    </div>
    <section className="mt-5 rounded-2xl border border-[var(--prism-border)] bg-[var(--prism-surface)] p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs tracking-[.18em] text-[var(--prism-cyan)]">REVENUE ENGINE</p><h2 className="font-medium">Demand → conversation → customer → growth</h2><p className="mt-1 text-xs text-[var(--prism-muted)]">COMIT is the internal machine for taking Lunes AI to market and learning from every action.</p></div><a href="/outreach" className="inline-flex items-center gap-2 rounded-xl border border-[var(--prism-border)] px-3 py-2 text-xs hover:bg-white/5">Open Revenue <ArrowUpRight size={14}/></a></div><div className="grid gap-3 sm:grid-cols-4">{[["Research","Find accounts"],["Qualify","Score the fit"],["Engage","Email + follow-up"],["Learn","Measure + improve"]].map(([a,b],i)=><div key={a} className="rounded-xl border border-[var(--prism-border)] p-4"><div className="text-xs text-[var(--prism-muted)]">0{i+1}</div><div className="mt-2 text-sm font-medium">{a}</div><div className="mt-1 text-xs text-[var(--prism-muted)]">{b}</div></div>)}</div></section>
    <section id="intelligence" className="mt-5 rounded-2xl border border-blue-400/20 bg-blue-500/[.035] p-5"><div className="flex items-center gap-2"><Bot size={18} className="text-blue-300"/><div><p className="text-xs tracking-[.18em] text-blue-300">COMIT INTELLIGENCE</p><h2 className="font-medium">Ask for the next Lunes AI growth action</h2><p className="text-xs text-[var(--prism-muted)]">Uses the existing AI route and frames every answer around Lunes AI growth.</p></div></div><div className="mt-4 flex gap-2"><input id="ai-input" value={aiInput} onChange={e=>setAiInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")askAI()}} placeholder="e.g. Find our next 10 high-fit customer segments" className="min-w-0 flex-1 rounded-xl border border-[var(--prism-border)] bg-black/20 px-3 py-3 text-sm outline-none focus:border-blue-400/50"/><button onClick={askAI} disabled={aiBusy} className="orbit-gradient rounded-xl px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{aiBusy?"Thinking…":"Ask COMIT"}</button></div>{aiResult&&<pre className="mt-4 max-h-72 overflow-auto rounded-xl border border-[var(--prism-border)] bg-black/20 p-4 text-xs whitespace-pre-wrap">{JSON.stringify(aiResult,null,2)}</pre>}</section>
    <section className="mt-5 rounded-2xl border border-[var(--prism-border)] bg-[var(--prism-surface)] p-5"><div className="flex items-center gap-3"><Activity size={18} className="text-blue-300"/><div><p className="text-xs tracking-[.18em] text-[var(--prism-cyan)]">TEAM RHYTHM</p><p className="mt-1 text-sm text-[var(--prism-muted)]">{nudge||"Every task should connect to product learning, customer conversations, revenue or operational leverage."}</p></div></div></section>
    <div className="mt-5 flex gap-2 overflow-x-auto lg:hidden">{links.map(([href,label])=><a key={href} href={href} className="whitespace-nowrap rounded-full border border-[var(--prism-border)] px-4 py-2 text-xs">{label}</a>)}</div>
    <footer className="mt-8 flex flex-wrap items-center justify-between gap-3 border-t border-[var(--prism-border)] pt-5 text-xs text-[var(--prism-muted)]"><span>COMIT · Internal Growth Operating System for Lunes AI</span><span className="flex items-center gap-3"><a href="https://instagram.com/prismofstories" target="_blank" rel="noreferrer"><Instagram size={14}/></a><a href="https://wa.me/919745643726" target="_blank" rel="noreferrer"><MessageCircle size={14}/></a><a href="mailto:prismofstories25@gmail.com"><Mail size={14}/></a></span></footer>
   </div>
  </section>
 </main>
}
