"use client";
import {useEffect,useMemo,useState} from "react";
import {ArrowUpRight,CheckCircle2,Clock3,Mail,MessageSquareReply,RefreshCw,Send,Target,Utensils,Users, XCircle} from "lucide-react";

type DashboardData={
  metrics:any;
  recent:any[];
  replies:any[];
  followups:any[];
  topTargets:any[];
};

function fmtDate(value:string){return new Intl.DateTimeFormat("en-IN",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(value))}
function dueLabel(value:string){const diff=new Date(value).getTime()-Date.now();if(diff<=0)return "Due now";const days=Math.ceil(diff/86400000);return `Due in ${days}d`}

export default function OutreachDashboard(){
  const [data,setData]=useState<DashboardData|null>(null);const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");const [busy,setBusy]=useState("");const [syncing,setSyncing]=useState(false);
  async function load(){setLoading(true);try{const r=await fetch("/api/outreach/dashboard",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not load dashboard");setData(d)}catch(e:any){setMessage(e.message||"Dashboard unavailable")}finally{setLoading(false)}}
  useEffect(()=>{load()},[]);
  async function syncGmail(){setSyncing(true);setMessage("");try{const r=await fetch("/api/outreach/reconcile",{method:"POST"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Gmail sync failed");setMessage(`Gmail synced: ${d.newReplies||0} new replies matched.`);await load()}catch(e:any){setMessage(e.message||"Gmail sync failed")}finally{setSyncing(false)}}
  async function action(payload:any){setBusy(String(payload.followupId||payload.prospectId||payload.action));setMessage("");try{const r=await fetch("/api/outreach/dashboard",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Action failed");setMessage(d.message||"Done");await load()}catch(e:any){setMessage(e.message||"Action failed")}finally{setBusy("")}}
  const m=data?.metrics;
  return <main className="min-h-screen p-5 lg:p-8"><div className="mx-auto max-w-7xl"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm text-[var(--prism-muted)]">REVENUE ENGINE</p><h1 className="mt-1 text-3xl font-semibold">Outreach command center</h1><p className="mt-2 text-sm text-[var(--prism-muted)]">Research → outreach → reply → follow-up → meeting → revenue.</p></div><div className="flex gap-2"><button onClick={syncGmail} disabled={syncing} className="inline-flex items-center gap-2 rounded-xl border border-[var(--prism-border)] px-3 py-2 text-sm"><Mail size={15}/>{syncing?"Syncing…":"Sync Gmail"}</button><button onClick={load} className="inline-flex items-center gap-2 rounded-xl border border-[var(--prism-border)] px-3 py-2 text-sm"><RefreshCw size={15}/>Refresh</button></div></div>
  {message&&<div className="mt-4 rounded-xl border border-[var(--prism-border)] p-3 text-sm">{message}</div>}
  <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Sent",m?.sent||0,Send],["Replies",m?.actualReplies||0,MessageSquareReply],["Reply rate",`${m?.replyRate||0}%`,Target],["Follow-ups",m?.pendingFollowups||0,Clock3],["Restaurant targets",m?.restaurantTargets||0,Utensils]].map(([label,value,Icon]:any)=><div key={label} className="rounded-2xl border border-[var(--prism-border)] bg-[var(--prism-surface)] p-4"><Icon size={16}/><div className="mt-3 text-2xl font-semibold">{value}</div><div className="mt-1 text-xs text-[var(--prism-muted)]">{label}</div></div>)}</div>
  <section className="mt-4 rounded-2xl border border-[var(--prism-border)] bg-[var(--prism-surface)] p-5"><div className="flex items-center justify-between"><div><p className="text-xs text-[var(--prism-muted)]">GMAIL RECONCILIATION</p><h2 className="mt-1 font-semibold">Incoming replies</h2></div><span className="text-xs text-[var(--prism-muted)]">Matched automatically</span></div><div className="mt-4 space-y-2">{(data?.replies||[]).map((r:any)=><div key={r.id} className="rounded-xl border border-[var(--prism-border)] p-3"><div className="flex flex-col gap-1 sm:flex-row sm:items-start sm:justify-between"><div><div className="text-sm font-medium">{r.prospects?.name||r.sender_email}</div><div className="text-xs text-[var(--prism-muted)]">{r.sender_email} · {r.subject||"Reply"}</div></div><div className="text-xs text-[var(--prism-muted)]">{fmtDate(r.received_at)}</div></div><p className="mt-2 text-sm text-[var(--prism-muted)]">{r.snippet||"Reply received."}</p></div>)}{!(data?.replies||[]).length&&<div className="rounded-xl border border-dashed border-[var(--prism-border)] p-6 text-center text-sm text-[var(--prism-muted)]">No matched campaign replies yet. Use Sync Gmail to check now.</div>}</div></section>
  <section className="mt-4 grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><div className="rounded-2xl border border-[var(--prism-border)] bg-[var(--prism-surface)] p-5"><h2 className="font-semibold">Recent outreach</h2><div className="mt-4 space-y-2">{(data?.recent||[]).slice(0,20).map((r:any)=><div key={r.id} className="rounded-xl border border-[var(--prism-border)] p-3"><div className="flex justify-between gap-3"><div><div className="text-sm font-medium">{r.prospects?.name||r.to_email}</div><div className="text-xs text-[var(--prism-muted)]">{r.subject}</div></div><div className="text-xs text-[var(--prism-muted)]">{fmtDate(r.created_at)}</div></div></div>)}</div></div><div className="rounded-2xl border border-[var(--prism-border)] bg-[var(--prism-surface)] p-5"><h2 className="font-semibold">Next actions</h2><div className="mt-4 space-y-2">{(data?.followups||[]).filter((x:any)=>x.status==="pending").slice(0,12).map((f:any)=><div key={f.id} className="rounded-xl border border-[var(--prism-border)] p-3"><div className="text-sm font-medium">{f.prospects?.name||"Prospect"}</div><div className="mt-1 text-xs text-[var(--prism-muted)]">{f.subject||"Follow-up"} · {dueLabel(f.due_at)}</div><button disabled={!!busy} onClick={()=>action({action:"send_followup",followupId:f.id})} className="mt-2 inline-flex items-center gap-2 rounded-lg border border-[var(--prism-border)] px-2 py-1 text-xs"><Send size={12}/>Send</button></div>)}</div></div></section>
  </div></main>
}
