"use client";
import {useEffect,useState} from "react";
import {MessageCircle,ShieldCheck,CheckCircle2,Target,Workflow,Clock3} from "lucide-react";

const fallback=[
 {name:"Amal",email:"amalpradeep25@gmail.com",role:"Founder · Command",focus:"Revenue, approvals, strategy",initials:"AP",logo_key:"prism",color_token:"amber",daily_target:"3 high-value decisions",automation_lane:"command"},
 {name:"Aadil",email:"aadil.sudhir279@gmail.com",role:"Sales · Outreach",focus:"Prospecting, qualification, follow-ups",initials:"AS",logo_key:"sales",color_token:"blue",daily_target:"20 qualified prospects + follow-ups",automation_lane:"sales"},
 {name:"Aneesh",email:"msaneeshnath@gmail.com",role:"Creative · Growth",focus:"Posters, carousels, reels, client creative growth",initials:"AN",logo_key:"creative",color_token:"violet",daily_target:"3 revenue-focused creatives",automation_lane:"creative"},
 {name:"Jishnu",email:"jishnu@prismofstories.com",role:"Operations · Client Growth",focus:"Delivery, client growth, systems and QA",initials:"JI",logo_key:"operations",color_token:"emerald",daily_target:"5 delivery/retention actions",automation_lane:"operations"},
 {name:"Shahid (Shahdi)",email:"shahidruiz01@gmail.com",phone:"+971 56 230 2610",role:"Video Production · Creative Production",focus:"Video shoots, production, edits, spot edits and related creative-production work",initials:"SH",logo_key:"video",color_token:"blue",daily_target:"Capture, produce and deliver priority video assets",automation_lane:"video"}
];
const logoClass:any={amber:"border-amber-300/30 bg-amber-300/10",blue:"border-sky-300/30 bg-sky-300/10",violet:"border-violet-300/30 bg-violet-300/10",emerald:"border-emerald-300/30 bg-emerald-300/10"};
export default function Team(){
 const [wa,setWa]=useState<any>({}),[members,setMembers]=useState<any[]>(fallback),[templates,setTemplates]=useState<any[]>([]),[done,setDone]=useState<string[]>([]);
 useEffect(()=>{Promise.all([fetch("/api/whatsapp").then(r=>r.json()),fetch("/api/team").then(r=>r.ok?r.json():null).catch(()=>null)]).then(([w,t])=>{setWa(w||{});if(t?.members?.length)setMembers(t.members);if(t?.templates)setTemplates(t.templates)}).catch(()=>{})},[]);
 const taskFor=(m:any)=>templates.find(t=>t.team_profile_id===m.id||t.workflow_key===`morning.${m.automation_lane}`)||templates.find(t=>String(t.title).toLowerCase().includes(String(m.automation_lane||"").toLowerCase()));
 return <main className="min-h-screen p-5 lg:p-8"><div className="mx-auto max-w-6xl">
  <div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm text-[var(--prism-muted)]">TEAM OS</p><h1 className="mt-1 text-3xl font-semibold">People, ownership & automation</h1><p className="mt-2 max-w-2xl text-sm text-[var(--prism-muted)]">Every teammate has a clear revenue lane, a COMIT profile, an individual morning outcome and an automation path. Tasks should move from owner → action → evidence → next step.</p></div><div className="rounded-xl border border-[var(--prism-border)] px-3 py-2 text-xs text-[var(--prism-muted)]"><Workflow size={14} className="mr-1 inline"/>Automation-first team OS</div></div>
  <div className="mt-7 grid gap-4 md:grid-cols-2">{members.map(m=>{const task=taskFor(m);return <article key={m.email} className="rounded-2xl border border-[var(--prism-border)] bg-[var(--prism-surface)] p-5 shadow-sm"><div className="flex items-start gap-4"><div className={`grid h-14 w-14 shrink-0 place-items-center rounded-2xl border ${logoClass[m.color_token]||"border-white/10 bg-white/5"}`}><div className="text-sm font-bold tracking-wide">{m.initials}</div></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h2 className="font-semibold">{m.name}</h2>{m.name==="Amal"&&<ShieldCheck size={15}/>}</div><p className="text-sm text-[var(--prism-muted)]">{m.role}</p><p className="mt-3 text-sm">{m.focus}</p><p className="mt-2 text-xs text-[var(--prism-muted)]">{m.email}</p>{m.phone&&<p className="mt-1 text-xs text-[var(--prism-muted)]">{m.phone}</p>}</div></div><div className="mt-4 rounded-xl border border-[var(--prism-border)] p-3"><div className="flex items-center gap-2 text-xs font-medium"><Target size={14}/>Daily outcome</div><p className="mt-1 text-sm">{m.daily_target}</p></div>{task&&<div className="mt-3 rounded-xl border border-[var(--prism-border)] p-3"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2 text-xs font-medium"><Clock3 size={14}/>Morning task · {String(task.priority).toUpperCase()}</div><span className="text-xs text-[var(--prism-muted)]">{task.due_hour}:00</span></div><p className="mt-1 text-sm font-medium">{task.title}</p><p className="mt-1 text-xs text-[var(--prism-muted)]">{task.description}</p></div>}<div className="mt-4 flex flex-wrap gap-2"><a href={m.name==="Amal"?"https://wa.me/"+(wa.public?.number||"919745643726"):wa.team?.[m.name]?"https://wa.me/"+wa.team[m.name]:"#"} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl border border-[var(--prism-border)] px-3 py-2 text-xs"><MessageCircle size={14}/>WhatsApp</a><button onClick={()=>setDone([...new Set([...done,m.email])])} className="inline-flex items-center gap-2 rounded-xl border border-[var(--prism-border)] px-3 py-2 text-xs">{done.includes(m.email)&&<CheckCircle2 size={14}/>} {done.includes(m.email)?"Check-in logged":"Log check-in"}</button>{m.email==="shahidruiz01@gmail.com"&&<a href="/creative-library" className="inline-flex items-center gap-2 rounded-xl border border-[var(--prism-border)] px-3 py-2 text-xs"><Target size={14}/>Open creative library</a>}</div></article>})}</div>
  <section className="mt-6 rounded-2xl border border-[var(--prism-border)] bg-[var(--prism-surface)] p-5"><p className="text-xs text-[var(--prism-muted)]">PROCESS AUTOMATION</p><h2 className="mt-1 font-semibold">How COMIT should run the team</h2><div className="mt-4 grid gap-3 md:grid-cols-4">{[["01","Research","COMIT finds prospects, signals and client risks"],["02","Assign","Each opportunity gets one owner and one next action"],["03","Execute","Gmail, n8n and task workflows reduce repetitive work"],["04","Prove","Replies, meetings, delivery and revenue update the scorecard"]].map(([n,t,d])=><div key={n} className="rounded-xl border border-[var(--prism-border)] p-3"><span className="text-xs text-[var(--prism-muted)]">{n}</span><div className="mt-1 font-medium">{t}</div><p className="mt-1 text-xs text-[var(--prism-muted)]">{d}</p></div>)}</div></section>
 </div></main>
}