"use client";

import {useEffect,useState} from "react";
import Link from "next/link";
import {CheckCircle2,Clock3,MessageCircle,ShieldCheck,Target,Workflow} from "lucide-react";

type Member={id:string;name:string;email?:string;phone?:string;role:string;focus:string;initials:string;color_token:string;daily_target:string;automation_lane:string};
type Checkin={memberId:string;at:string};
const STORAGE_KEY="comit.teamCheckins.v1";
const fallback:Member[]=[
  {id:"amal",name:"Amal",role:"Founder · Command",focus:"Revenue, approvals, strategy",initials:"AP",color_token:"amber",daily_target:"3 high-value decisions",automation_lane:"command"},
  {id:"aadil",name:"Aadil",role:"Sales · Outreach",focus:"Prospecting, qualification, follow-ups",initials:"AS",color_token:"blue",daily_target:"20 qualified prospects + follow-ups",automation_lane:"sales"},
  {id:"aneesh",name:"Aneesh",role:"Creative · Growth",focus:"Posters, carousels, reels, client creative growth",initials:"AN",color_token:"violet",daily_target:"3 revenue-focused creatives",automation_lane:"creative"},
  {id:"jishnu",name:"Jishnu",role:"Operations · Client Growth",focus:"Delivery, client growth, systems and QA",initials:"JI",color_token:"emerald",daily_target:"5 delivery/retention actions",automation_lane:"operations"},
  {id:"shahid",name:"Shahid (Shahdi)",email:"shahidruiz01@gmail.com",phone:"+971 56 230 2610",role:"Video Production · Creative Production",focus:"Video shoots, production, edits, spot edits and related creative-production work",initials:"SH",color_token:"blue",daily_target:"Capture, produce and deliver priority video assets",automation_lane:"video"},
];
const colorClass:Record<string,string>={amber:"border-amber-300/30 bg-amber-300/10",blue:"border-sky-300/30 bg-sky-300/10",violet:"border-violet-300/30 bg-violet-300/10",emerald:"border-emerald-300/30 bg-emerald-300/10"};
function readCheckins():Checkin[]{try{const parsed=JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]");return Array.isArray(parsed)?parsed:[]}catch{return[]}}
function phoneHref(value:string){const digits=value.replace(/\D/g,"");return digits.length>=8?`https://wa.me/${digits}`:""}

export default function Team(){
  const [members]=useState<Member[]>(fallback),[checkins,setCheckins]=useState<Checkin[]>([]),[message,setMessage]=useState("");
  useEffect(()=>{setCheckins(readCheckins())},[]);
  function logCheckin(memberId:string){const next=[...readCheckins(),{memberId,at:new Date().toISOString()}].slice(-300);localStorage.setItem(STORAGE_KEY,JSON.stringify(next));setCheckins(next);setMessage("Check-in saved in this browser on this device.")}
  return <main className="min-h-screen bg-[var(--prism-bg)] p-5 pb-24 text-[var(--prism-text)] lg:p-8"><a href="/team/shared" className="mb-4 inline-block text-xs text-[var(--prism-muted)] underline">Connected team workspace (sign-in required)</a><div className="mx-auto max-w-6xl">
    <div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs tracking-wide text-[var(--prism-muted)]">TEAM OS</p><h1 className="mt-1 text-3xl font-semibold">People, ownership & automation</h1><p className="mt-2 max-w-2xl text-sm text-[var(--prism-muted)]">Each teammate has a clear lane and outcome. Check-ins are saved locally until a no-cost shared store is configured.</p></div><div className="rounded-xl border border-[var(--prism-border)] px-3 py-2 text-xs text-[var(--prism-muted)]"><Workflow size={14} className="mr-1 inline"/>Local-first team workspace</div></div>
    {message&&<p role="status" className="mt-4 rounded-xl border border-[var(--prism-border)] p-3 text-sm">{message}</p>}
    <div className="mt-7 grid gap-4 md:grid-cols-2">{members.map(member=>{const number=member.phone||(member.name==="Amal"?"919745643726":""),href=phoneHref(number),isDone=checkins.some(item=>item.memberId===member.id&&new Date(item.at).toDateString()===new Date().toDateString());return <article key={member.id} className="rounded-2xl border border-[var(--prism-border)] bg-[var(--prism-surface)] p-5 shadow-sm"><div className="flex items-start gap-4"><div className={`grid h-14 w-14 shrink-0 place-items-center rounded-2xl border ${colorClass[member.color_token]||"border-white/10 bg-white/5"}`}><span className="text-sm font-bold tracking-wide">{member.initials}</span></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h2 className="font-semibold">{member.name}</h2>{member.name==="Amal"&&<ShieldCheck size={15}/>}</div><p className="text-sm text-[var(--prism-muted)]">{member.role}</p><p className="mt-3 text-sm">{member.focus}</p>{member.email&&<p className="mt-2 text-xs text-[var(--prism-muted)]">{member.email}</p>}{member.phone&&<p className="mt-1 text-xs text-[var(--prism-muted)]">{member.phone}</p>}</div></div>
      <div className="mt-4 rounded-xl border border-[var(--prism-border)] p-3"><div className="flex items-center gap-2 text-xs font-medium"><Target size={14}/>Daily outcome</div><p className="mt-1 text-sm">{member.daily_target}</p></div>
      <div className="mt-4 flex flex-wrap gap-2">{href?<a href={href} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl border border-[var(--prism-border)] px-3 py-2 text-xs"><MessageCircle size={14}/>WhatsApp</a>:<span className="inline-flex items-center gap-2 rounded-xl border border-[var(--prism-border)] px-3 py-2 text-xs text-[var(--prism-muted)]" aria-disabled="true"><MessageCircle size={14}/>Contact not configured</span>}<button onClick={()=>logCheckin(member.id)} className="inline-flex items-center gap-2 rounded-xl border border-[var(--prism-border)] px-3 py-2 text-xs">{isDone&&<CheckCircle2 size={14}/>} {isDone?"Check-in logged today":"Log check-in"}</button>{member.id==="shahid"&&<Link href="/creative-library" className="inline-flex items-center gap-2 rounded-xl border border-[var(--prism-border)] px-3 py-2 text-xs"><Target size={14}/>Open creative library</Link>}</div>
    </article>})}</div>
    <section className="mt-6 rounded-2xl border border-[var(--prism-border)] bg-[var(--prism-surface)] p-5"><p className="text-xs text-[var(--prism-muted)]">PROCESS AUTOMATION</p><h2 className="mt-1 font-semibold">How COMIT should run the team</h2><div className="mt-4 grid gap-3 md:grid-cols-4">{[["01","Research","Use evidence and keep assumptions labeled"],["02","Assign","Give each next action one owner"],["03","Execute","Keep external actions approval-gated"],["04","Prove","Record outcomes before updating scorecards"]].map(([n,title,description])=><div key={n} className="rounded-xl border border-[var(--prism-border)] p-3"><span className="text-xs text-[var(--prism-muted)]">{n}</span><div className="mt-1 font-medium">{title}</div><p className="mt-1 text-xs text-[var(--prism-muted)]">{description}</p></div>)}</div></section>
  </div></main>;
}
